### ISSUE TITLE
BasalUnit 1.0.4

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#302]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=186124269)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1816028149

**Comment by herr-zett** [comment]
This software is missing an actual documentation, which is why I couldn't fill in all necessary information.

**Comment by jagru20** [comment]
we will ask the developer

**Comment by appukuttan-shailesh** [comment]
Thanks for tagging me on this. I have now filled up the missing info (fields that were in red and empty).
Let me know if you need any other info.

**Comment by herr-zett** [comment]
@appukuttan-shailesh Thank you so far for your contributions! Would you be so kind to provide some of the additional information, especially regarding the software features as well as input/output formats?

**Comment by appukuttan-shailesh** [comment]
Done :+1:

**Comment by jagru20** [comment]
Thank you for your help so far, @appukuttan-shailesh. 
Unfortunately there are still some questions that we cannot find the answer to (see the "Comments" Column in the spreadsheet):

- [ ] The setup-file says that the software is licensed under the MIT-license and therefore contradicts the provided license-file
- [ ] The developer's spreadsheet says version 1.0.3, which contradicts the latest release on GitHub. Furthermore this setup-file from the master-tree on GitHub says that the version of this software is actually 1.0.4

Could you please clarify, wich license is the correct one and fill in the correct version number? If it's already correct just let us know. 

Moreover it would be amazing if you could have a quick look at the [List of Software Features](https://github.com/bweyers/HBPVisCatalogue/wiki/Identified-Software-Features) and fill in field B29 with applicable info according to the descriptions given in the List, if you have time to.

@bweyers: I would suggest adding a new usage to the list as this software's purpose seems to be model validation, which is not yet listed in the [Identified Software Features](https://github.com/bweyers/HBPVisCatalogue/wiki/Identified-Software-Features)

**Comment by appukuttan-shailesh** [comment]
Thanks for the detailed response @jagru20 

The license is indeed "BSD-3-Clause License", and the mistake is in "setup.py". We shall rectify this during the next release.
The latest version (as on PyPI) is 1.0.4.

I have updated both of these in the spreadsheet, along with best fits for the field in B29.

Thanks for your efforts.

**Comment by jagru20** [comment]
Dear @appukuttan-shailesh, sorry for bothering you again, but somehow the Software Features are still missing, would you please  have another look at this? Thank you very much.

**Comment by appukuttan-shailesh** [comment]
That is weird.... the changes for cel lB13 were saved, but not for cell B29. I could not even locate it in the sheet history.
Anyways, have done it again.

Pasting it here just as backup:

> Data Types: Abstract
> Usage: Simulation
> Display: Desktop Environment
> User Interface: Commandline Interface
> System Architecture: Heterogeneous Architecture
> Development: Parallel Programming

Thanks again for your time on this.

**Comment by jagru20** [comment]
Thank you very much! @herr-zett, please integrate.

**Comment by herr-zett** [comment]
Regarding the abstract data types I've chosen "Graph Data Types" and "Time Series Data Types" as they seemed most suitable to me. If this is incorrect or incomplete the KG-entry needs to be updated.

Furthermore I didn't include the feature "Parallel Programming" yet. In my understanding we intended the feature category "Development" for software that can be used to develop other software.

**Comment by jagru20** [comment]
has been released
